### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by kalmarek** [bprzybylski/KB.jl#1]
# Milestone 1
- [x] Make this work:
```julia

kb_data_dir = joinpath("deps", "src", "kbmag-1.5.6", "standalone", "kb_data")

kb_examples = readdir(kb_data_dir)
ex = joinpath(kb_data_dir, kb_examples[1])

rws = KB.RewritingSystem()
[...]
ccall((:read_kbinput, KB.fsalib), Cvoid, (Cstring, Bool, Ptr{KB.RewritingSystem}), ex, true, Ref(rws))

```
# Milestone 2
- [x] working `ccall((:kbprog, KB.fsalib), Cint, (Ptr{KB.RewritingSystem}), Ref(rws))`
- [x] writing/reading `kbmag` compatible files (from julia)
- [x] reduction of words via call to `int rws_reduce(gen *w, reduction_struct *rs_rws);`
- [x] tests from `kb_data`

# Milestone 3
Integration with `Groups.jl`:
 - [ ] redesign the `FPGroup` from `Groups.jl` to allow _letter-based_ representation of words (currently it's syllable-based)
 - [ ] generating input for `ccall((:kbprog, KB.fsalib), ... )` from `FPGroup` (as defined in `Groups.jl`)
 - [ ] different orderings from the level of `FPGroups`
 - [ ] `KBOptions` struct to be passed along a `FPgroup`??

**Comment by kalmarek** [comment]
example syntax:
```julia
using Pkg
Pkg.add("AbstractAlgebra")
Pkg.add("https://github.com/kalmarek/Groups.jl")
Pkg.pin("Groups")
```

```julia
using Groups, AbstractAlgebra
F = FreeGroup(["a", "b", "c"]);
a,b,c = gens(F);
R = [a^7, b^3, c^2, a*b*c]
G = F/R
```
Aim: implement 
```julia
function RewritingSystem(G::Groups.FPGroup; order="shortlex", blah....)
    ...
    return rws::KBMag.RewritingSystem
end
```
